source "http://rubygems.org"
gem 'slack-ruby-client', '~> 0.7'
gem 'dogapi',  '~> 1.23'
gem 'virtus',  '~> 1.0'
gem 'facets',  '~> 3.1'
gem 'thor',    '~> 0.19'
gem 'aws-sdk', '~> 2.6'
gem 'json',    '~> 2.0'
gem 'webrick', '~> 1.4.2'
gem 'bigdecimal'
